# Copyright 2021 Hyperledger Community
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
 

version: "3.6"

services:
  github-contributors-action:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: github-contributors-action
    environment:
      - GITHUB_AUTH_TOKEN=${GITHUB_AUTH_TOKEN}
      - SOURCE_GITHUB_REPOSITORY=hyperledger-tooling/github-contributors-action
      - CONTRIBUTORS_SECTION_PATTERN=## Contributors
      - CONTRIBUTORS_SECTION_END_PATTERN=## Contributions
      - INPUT_TEMPLATE_FILE=/assets/minimal.md
      - FILE_WITH_PATTERN=/README.md
    volumes:
      - ../assets:/assets
      - ../README.md:/README.md

  github-org-all-contributors:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: github-org-all-contributors
    environment:
      - GITHUB_AUTH_TOKEN=${GITHUB_AUTH_TOKEN}
      - SOURCE_GITHUB_REPOSITORY=hyperledger-tooling
      - CONTRIBUTORS_SECTION_PATTERN=# Hyperledger Tooling All Contributors
      ## In case of no end pattern, end of file is considered
      - CONTRIBUTORS_SECTION_END_PATTERN=
      - INPUT_TEMPLATE_FILE=/assets/minimal.md
      - FILE_WITH_PATTERN=/all-contributors.md
    volumes:
      - ../assets:/assets
      - ../all-contributors.md:/all-contributors.md
